name: Docker Build Check

on:
  push:
    branches: [ "main" ]  # Запускать при каждом пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-test-app .

      - name: Check Container Status
        run: |
          docker run -d --name test-container -p 8080:80 my-test-app
          sleep 5
          curl --silent --fail http://localhost:8080 || exit 1
          echo "Check passed!"
